import { PolicyPage } from "@/components/policy-page";
import { pageMetadata } from "@/lib/metadata";

export const metadata = pageMetadata({
  path: "/sourcing-policy",
  title: "Sourcing policy",
  description:
    "The source hierarchy LogisticID Magazine works from, how citations are recorded, and what it will not treat as evidence.",
});

export default function SourcingPolicyPage() {
  return (
    <PolicyPage
      path="/sourcing-policy"
      standfirst="Every material factual claim in LogisticID Magazine is tied to a source a reader can open and check. This page describes which sources count and how they are recorded."
      title="Sourcing policy"
    >
      <h2 id="hierarchy">The source hierarchy</h2>
      <p>Material factual claims are supported from the highest available tier:</p>
      <ol>
        <li>EU institutions and EUR-Lex, for European law;</li>
        <li>national transport, customs and other public authorities;</li>
        <li>UNECE and other intergovernmental bodies;</li>
        <li>Eurostat and national statistics offices;</li>
        <li>recognised research institutions and peer-reviewed literature;</li>
        <li>standards bodies, where the material is publicly accessible;</li>
        <li>the IRU and comparable sector institutions;</li>
        <li>official infrastructure and operator documentation;</li>
        <li>first-party company announcements, for facts about that company;</li>
        <li>manufacturer technical documentation, for equipment specifics.</li>
      </ol>
      <p>
        Trade press may point towards a development, but it is used to find the primary source
        rather than to stand in for it.
      </p>

      <h2 id="not-evidence">What is not treated as evidence</h2>
      <p>
        Factual articles are not built on SEO blogs, affiliate pages, anonymous carrier blogs,
        scraped summaries, content aggregators or AI-generated summaries. These reliably reproduce
        each other&rsquo;s errors, and a claim that appears in twenty of them is not thereby
        confirmed twenty times.
      </p>

      <h2 id="paywalled">Sources that could not be read in full</h2>
      <p>
        Some standards and reports are paid or otherwise inaccessible. Where only an abstract,
        summary or table of contents was available, the reference says so explicitly and the article
        does not present the full text as having been read. Claiming to have read a standard that
        was not opened is the quiet form of fabrication that is hardest for a reader to detect.
      </p>

      <h2 id="citations">How citations work here</h2>
      <p>
        Citations are numbered in the text and resolve to a reference list rendered in the page
        itself, not loaded afterwards. Each reference records the responsible author or
        organisation, the title, the publication, the date, an identifier where one exists, and the
        date the source was actually consulted.
      </p>
      <p>
        Access dates are recorded by a person opening the source. They are never generated by the
        build, and never set to the date of publication as a convenience — a fabricated access date
        is a false claim about editorial work that was not done.
      </p>
      <p>
        The build enforces both directions of this: an article that cites a source it does not list
        will not publish, and an article that lists a source it never cites will not publish either.
        The second rule matters as much as the first, because a bibliography of unused authorities
        borrows their credibility without doing the work.
      </p>

      <h2 id="time-sensitive">Time-sensitive material</h2>
      <p>
        Legal, regulatory, market and news claims change. Articles covering them state the
        jurisdiction and the date the position was checked, and they are re-checked rather than
        quietly left in place. Where a position may have moved since it was checked, the article
        says to verify it rather than implying it still holds.
      </p>
    </PolicyPage>
  );
}
